language: go

# github.com/flynn/hid is broken on go1.12 on MacOS X, so pin to go1.11.x
go:
    - 1.13.x

os:
    - linux

before_install:
    - go get github.com/mattn/goveralls
    - go get github.com/pquerna/otp/totp
    - REPO_NAME=$(basename $PWD)
    - echo $PWD
    - GITHUB_PATH=$(dirname $(dirname $PWD))
    - echo $GITHUB_PATH
    - SYMANTEC_PROJECT_DIR=${GITHUB_PATH}/sidgod/${REPO_NAME}
    - echo $SYMANTEC_PROJECT_DIR
    - mkdir -p ${SYMANTEC_PROJECT_DIR}
    - rsync -az ${TRAVIS_BUILD_DIR}/ ${SYMANTEC_PROJECT_DIR}/
    - export TRAVIS_BUILD_DIR=${SYMANTEC_PROJECT_DIR}
    - cd ${SYMANTEC_PROJECT_DIR}

install: make get-deps

script:
    - go test -v -covermode=count -coverprofile=coverage.out ./...
    - make all test
